# -*- coding: utf-8 -*-
"""FinalYear_project_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2T6XJj5cAUUcMBmaAzCgOZ3x9yYNkij
"""

def classify_aqi(aqi_value):
    if 0 <= aqi_value <= 50:
        return "Good"
    elif 51 <= aqi_value <= 100:
        return "Moderate"
    elif 101 <= aqi_value <= 150:
        return "Unhealthy for Sensitive Groups"
    elif 151 <= aqi_value <= 200:
        return "Unhealthy"
    elif 201 <= aqi_value <= 300:
        return "Very Unhealthy"
    elif aqi_value >= 301:
        return "Hazardous"
    else:
        return "Invalid AQI Value"

import pickle

file_name = 'classify_aqi_function.pkl'

with open(file_name, 'wb') as f:
    pickle.dump(classify_aqi, f)

print(f"The function 'classify_aqi' has been dumped to '{file_name}' successfully.")